wallpaper {
    monitor = eDP-1
    path = ~/home/sarcutus/Pictures/yor_forger_bloom_of_the_blade_by_viciouza_dlce13m-pre.jpg
    fit_mode = cover
}

# wallpaper {
#     monitor = DP-2
#     path = ~/myFile2.jxl
#     fit_mode = cover
# }

wallpaper {
    monitor = 
    path = /home/sarcutus/Pictures/dg02uud-21dfb89e-2442-4f5e-8443-5effac68be6b.png
    fit_mode = cover
}

# ...
